# Generated by Django 5.1 on 2024-09-02 16:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=50)),
                ('made_by', models.CharField(default='user_made', max_length=50)),
                ('usage', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('payments', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('images', models.IntegerField(default=200)),
                ('videos', models.IntegerField(default=100)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='members.member')),
            ],
        ),
    ]
