# Generated by Django 5.1 on 2024-09-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_account_payments_alter_account_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='images',
        ),
        migrations.RemoveField(
            model_name='account',
            name='videos',
        ),
    ]
